image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - push
  - test

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_app:$CI_PIPELANE_ID ./server/
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_proxy:$CI_PIPELANE_ID ./proxy/

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up

push:
  stage: push
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker push -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_app:$CI_PIPELANE_ID ./server/
    - docker push -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_proxy:$CI_PIPELANE_ID ./proxy/