image: docker:19.03.12

services:
  - docker:19.03.12-dind



stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from app
  only:
    - master

build_app:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/app:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID ./server/
    - docker push ${CI_REGISTRY_IMAGE}/app:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  after_script:
    - docker logout
  needs:
    - test
  only:
    - master

deploy:
  stage: deploy  
  image: lwolf/helm-kubectl-docker:v1.21.1-v3.6.0
  before_script:
    - kubectl config set-cluster my-cluster --server="$K3S_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$K3S_TOKEN"
    - kubectl config set-context default-context --cluster=my-cluster --user=admin
    - kubectl config use-context default-context
  script:
    - helm upgrade --install $CI_PROJECT_PATH_SLUG .helm 
      --set app.tag=$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  only:
    - master
  needs:
    - build_app
