image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build 
  - test
  - deploy

build:
  stage: build
  before_script:  
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_app.$CI_PIPELINE_ID ./server/ 
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_app.$CI_PIPELINE_ID

    - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_proxy.$CI_PIPELINE_ID ./proxy/
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_proxy.$CI_PIPELINE_ID

test:
  stage: test
  script:
    - apk add --no-cache docker-compose
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from app

deploy:
  stage: deploy
#  environment:
#    DOCKER_HOST: tcp://docker:2375/
  script:
    - apk add --no-cache docker-compose
    - echo "deploy....."
  only:
    - master
  