image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID ./server/
    - docker push ${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID
    - docker build -t ${CI_REGISTRY_IMAGE}/app:latest ./server/
    - docker push ${CI_REGISTRY_IMAGE}/app:latest

    - docker build -t ${CI_REGISTRY_IMAGE}/proxy:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID ./proxy/
    - docker push ${CI_REGISTRY_IMAGE}/proxy:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID
    - docker build -t ${CI_REGISTRY_IMAGE}/proxy:latest ./proxy/
    - docker push ${CI_REGISTRY_IMAGE}/proxy:latest

    - docker build -t ${CI_REGISTRY_IMAGE}/prometheus:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID ./monitoring/prometheus/
    - docker push ${CI_REGISTRY_IMAGE}/prometheus:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID
    - docker build -t ${CI_REGISTRY_IMAGE}/prometheus:latest ./monitoring/prometheus/
    - docker push ${CI_REGISTRY_IMAGE}/prometheus:latest

test:
  stage: test
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from app

deploy:
  stage: deploy
  variable:
    DOCKER_HOST: tcp://zloi.space:2376
  before_script:
    - apk add --no-cache docker-compose
  script:    
    - docker-compose -f docker-compose.prod.yml pull
    - docker-compose -f docker-compose.prod.yml restart
#  only:
#    - master
