image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build 
  - test
  - deploy

build:
  stage: build
  before_script:  
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull ${CI_REGISTRY_IMAGE}_app:latest
    - docker build --cache-from ${CI_REGISTRY_IMAGE}_app:latest -t ${CI_REGISTRY_IMAGE}_app:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID ./server/   #azia_app:latest azia_proxy:latest
    - docker push ${CI_REGISTRY_IMAGE}_app:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID
    - docker push ${CI_REGISTRY_IMAGE}_app:latest

    - docker build -t ${CI_REGISTRY_IMAGE}_proxy:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID ./proxy/
    - docker push ${CI_REGISTRY_IMAGE}_proxy:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID
    - docker push ${CI_REGISTRY_IMAGE}_proxy:latest

    - docker build -t ${CI_REGISTRY_IMAGE}_prometheus:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID ./monitoring/prometheus/
    - docker push ${CI_REGISTRY_IMAGE}_prometheus:${CI_COMMIT_REF_SLUG}.$CI_PIPELINE_ID
    - docker push ${CI_REGISTRY_IMAGE}_prometheus:latest

test:
  stage: test
  script:
    - apk add --no-cache docker-compose
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from app

deploy:
  stage: deploy
#  environment:
#    DOCKER_HOST: tcp://docker:2375/
  script:
    - apk add --no-cache docker-compose
    - echo "deploy....."
  only:
    - master
  