image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - push
  - test

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_app.$CI_PIPELINE_ID ./server/ 
    - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_proxy.$CI_PIPELINE_ID ./proxy/

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up

push:
  stage: push
  before_script:  
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_app.$CI_PIPELINE_ID
    - docker push -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_app.$CI_PIPELINE_ID