version: "3.3"

services:
  app:
    image: registry.gitlab.com/zl0i/aziaserver/app:latest
    working_dir: /opt/server/
    volumes:
      - ./server/__test__:/opt/server/__test__
    command: sh -c "npm install && npm test"
           