version: "3.3"

services:
  app:
    image: registry.gitlab.com/zl0i/restaurantserver/app:latest
    working_dir: /opt/server/
    volumes:
      - ./server/__test__:/opt/server/__test__
      - ./server/package.json:/opt/server/package.json
    command: sh -c "npm install && npm test"
           