version: "3.3"

services:
  db:
    image: mongo:4.4.4-bionic
    container_name: db 
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APP_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE:  ${APP_MONGODB_DB}
    volumes: 
      - ./db/fakedata.js:/docker-entrypoint-initdb.d/initdb.js:ro
    networks:
     - backend  
    ports:
      - 27017:27017

  app:
    image: node:12.18.4-alpine
    working_dir: /opt/server/
    volumes:
      - ./server/:/opt/server/
    entrypoint: npm run start:dev
    env_file: ./.env
    networks:
     - backend  
    expose:
      - 3000
    restart: always

  nginx:
    image: nginx:1.19.2-alpine
    container_name: proxy
    volumes:
      - ./proxy/dev.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/static/:/var/www/static/     
      - ./proxy/ssl/:/etc/ssl/
    restart: always
    networks:
     - backend  
    ports:
      - 80:80
      - 443:443

networks: 
  backend:
    name: backend
    driver: bridge
