version: "3.3"

services:
  db:
    image: mysql:8.0.24
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/mysql     
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    ports:
      - 3306:3306     

  app:
    image: node:12.18.4-alpine
    working_dir: /opt/server/
    restart: always
    volumes:
      - ./server/:/opt/server/
    entrypoint: npm run start:dev
    env_file: ./.env
    networks:
      - backend
    expose:
      - 3000

  nginx:
    image: nginx:1.19.2-alpine
    container_name: proxy
    volumes:
      - ./proxy/dev.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/static/:/var/www/static/
      - ./proxy/ssl/:/etc/ssl/
    restart: always
    networks:
      - backend
    ports:
      - 80:80
      - 443:443

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db: {}
