version: "3.3"

services:
  db:
    image: mysql:8.0.24
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    ports:
      - 3306:3306

  minio:
    image: bitnami/minio:2021.6.17
    container_name: minio
    restart: always
    volumes: 
      - storage:/data
    environment:
      - MINIO_ACCESS_KEY=${STORAGE_USER}
      - MINIO_SECRET_KEY=${STORAGE_PASSWORD}
    networks:
      - backend
    port: 
      - 9000

  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    restart: always
    volumes: 
      - redis:/data
    networks: 
      - backend
    expose:
      - 6379

  app:
    image: registry.gitlab.com/zl0i/restaurantserver/app:latest
    restart: always
    env_file: ./.env
    expose:
      - 3000
    networks:
      - backend

  nginx:
    image: registry.gitlab.com/zl0i/restaurantserver/proxy:latest
    container_name: proxy
    restart: always
    networks:
      - backend
    ports:
      - 80:80
      - 443:443

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped
    expose:
      - 8080
    devices:
      - "/dev/kmsg"
    networks:
      - backend

  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - backend

  nginxexporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    container_name: nginxexporter
    command: -nginx.scrape-uri http://proxy:80/nginx_status
      -nginx.retries=10
      -web.telemetry-path=/metrics
    restart: unless-stopped
    expose:
      - 9113
    networks:
      - backend

  mysqlexporter:
    image: bitnami/mysqld-exporter:0.13.0
    container_name: mysqlexporter
    environment: 
      - DATA_SOURCE_NAME=root:${DB_PASSWORD}@(db:3306)/
    restart: unless-stopped
    expose: 
      - 9104
    networks: 
      - backend

  redisexporter:
    image: bitnami/redis-exporter:1.26.0
    restart: always
    container_name: redis-exporter
    environment: 
      - REDIS_ADDR=redis://redis:6379
    expose:
      - 9121
    networks: 
      - backend

  prometheus:
    image: registry.gitlab.com/zl0i/restaurantserver/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - ./monitoring/prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - backend

  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    user: root
    volumes:
      - ./monitoring/grafana/:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=zloi.space
      - GF_SERVER_ROOT_URL=https://zloi.space/restaurant/server/grafana
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - backend

volumes:
  db: {}
  redis: {}
  storage: {}

networks:
  backend:
    driver: bridge
