global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'prometheus-grafana-exporter'

scrape_configs:

  - job_name: "node"
    scrape_interval: 15s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: "cadvisor"
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['nginxexporter:9113']
  
  - job_name: 'mysql'
    scrape_interval: 15s
    static_configs:
      - targets: ['mysqlexporter:9104']
  
  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
    - targets: ['redis-exporter:9121']
  
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ3ODM4MDgwODEsImlzcyI6InByb21ldGhldXMiLCJzdWIiOiJ6bG9pIn0.VuhT85ynNR-ry0cwecYzwz1t6Xw-0RnD7ru7UpB0zZWnBw8gfjQ2f6hKyIIHEg3KplF46wCJtjfew62Sf_e1Mg
    scrape_interval: 15s
    static_configs:
    - targets: ['minio:9000']
      
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

