apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:    
    email: pdmitri07@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:     
      name: app-cert
    solvers:
    - http01:
        ingress:
          class: nginx